summary(head(iris))
mtcars %>% summary()

iris %>% summary()
iris %>% glimpse()

filter(iris, Species == "setosa")
iris3 <- iris %>% filter(Sepal.Length > 2)
dim(iris3)
iris3 <- iris %>% filter(Sepal.Length > 5.5)
dim(iris3)
iris3 <- iris %>% filter(Sepal.Length > 5.2)
dim(iris3)
iris3 <- iris %>% filter(Sepal.Length > 5.)
dim(iris3)
iris3 <- iris %>% filter(Sepal.Length > 5.4)
dim(iris3)
iris3 <- iris %>% filter(Sepal.Length > 5.6)
dim(iris3)
history(100)
